"""One authoritative problem-authoring and acceptance pipeline."""

from __future__ import annotations

import re
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from vbagent.authoring.agents import DefaultAuthoringAgents
from vbagent.authoring.models import (
    DiagramPolicy,
    GenerationSpec,
    SourceKind,
    VariantFamily,
)
from vbagent.authoring.novelty import NoveltyIndex
from vbagent.authoring.results import AuthoredCandidate, CandidateStatus, GateResult
from vbagent.authoring.structure import validate_draft_structure, validate_final_structure
from vbagent.pipeline.io import has_main_diagram_placeholder, replace_main_diagram_placeholder


class AuthoringPipeline:
    """Run a GenerationSpec through every required acceptance gate."""

    CONTRACT_VERSION = 1

    def __init__(
        self,
        agents: Any | None = None,
        novelty_index: NoveltyIndex | None = None,
        render_dir: str | Path | None = None,
    ):
        self.agents = agents or DefaultAuthoringAgents()
        self.novelty_index = novelty_index or NoveltyIndex()
        self.render_dir = str(Path(render_dir).resolve()) if render_dir else None

    def run(self, spec: GenerationSpec, retry_context: str | None = None) -> AuthoredCandidate:
        from vbagent.ui.logging import agent_logging_context, capture_agent_logging_context

        events: list[dict[str, Any]] = []
        current_logging = capture_agent_logging_context()
        with agent_logging_context(
            output_console=current_logging.console,
            quiet=current_logging.quiet,
            event_sink=events.append,
        ):
            candidate = self._run(spec, retry_context=retry_context)
        candidate.provenance["usage"] = _aggregate_usage(events)
        return candidate

    def _run(self, spec: GenerationSpec, retry_context: str | None = None) -> AuthoredCandidate:
        candidate = AuthoredCandidate(
            spec=spec,
            status=CandidateStatus.RUNNING,
            provenance={
                "authoring_contract_version": self.CONTRACT_VERSION,
                "spec_fingerprint": spec.fingerprint(),
                "agents": self.agents.provenance() if hasattr(self.agents, "provenance") else {},
            },
        )

        try:
            draft, elapsed = _timed(
                self.agents.generate_draft,
                spec,
                **({"retry_context": retry_context} if retry_context else {}),
            )
        except Exception as exc:
            return self._fail(candidate, "draft", exc)
        candidate.problem_latex = draft.problem_latex.strip()
        candidate.draft_solution_latex = draft.solution_latex.strip()
        candidate.idea_latex = (getattr(draft, "idea_latex", "") or "").strip()
        candidate.diagram_description = (getattr(draft, "diagram_description", "") or "").strip()
        candidate.generation_metadata = dict(getattr(draft, "generation_metadata", {}) or {})
        candidate.gates.append(
            GateResult(gate="draft", passed=True, summary="draft generated", duration_ms=elapsed)
        )

        structure_issues = validate_draft_structure(
            spec,
            candidate.problem_latex,
            candidate.draft_solution_latex,
            candidate.diagram_description,
        )
        if not self._gate(
            candidate,
            gate="structure",
            required=True,
            passed=not structure_issues,
            summary="draft structure is valid" if not structure_issues else "; ".join(structure_issues),
            data={"issues": structure_issues},
        ):
            return self._reject(candidate)

        if candidate.diagram_description and spec.diagram_policy is not DiagramPolicy.FORBIDDEN:
            try:
                diagram, elapsed = _timed(
                    self.agents.generate_problem_diagram,
                    spec,
                    candidate.problem_latex,
                    candidate.diagram_description,
                )
            except Exception as exc:
                return self._fail(candidate, "problem_diagram", exc)
            candidate.diagram_code = (diagram.get("code") or "").strip()
            if not candidate.diagram_code:
                return self._fail(candidate, "problem_diagram", RuntimeError("diagram agent returned no code"))
            candidate.problem_latex = _assemble_problem_diagram(
                candidate.problem_latex,
                candidate.diagram_code,
            )
            candidate.gates.append(
                GateResult(
                    gate="problem_diagram",
                    passed=True,
                    summary=f"problem diagram generated by {diagram.get('agent', 'unknown')}",
                    data={"agent": diagram.get("agent")},
                    duration_ms=elapsed,
                )
            )

        try:
            solved, elapsed = _timed(
                self.agents.solve_independently,
                spec,
                candidate.problem_latex,
                bool(candidate.diagram_code),
            )
        except Exception as exc:
            return self._fail(candidate, "independent_solution", exc)
        candidate.final_latex = solved.latex.strip()
        candidate.independent_solution_latex = _extract_solution(candidate.final_latex)
        candidate.provenance["independent_answer"] = {
            "answer_type": getattr(solved, "answer_type", None),
            "answer_value": getattr(solved, "answer_value", None),
            "final_answer_latex": getattr(solved, "final_answer_latex", None),
        }
        candidate.gates.append(
            GateResult(
                gate="independent_solution",
                passed=True,
                summary="independent solution generated",
                duration_ms=elapsed,
            )
        )

        final_issues = validate_final_structure(spec, candidate.final_latex)
        if not self._gate(
            candidate,
            gate="final_structure",
            required=True,
            passed=not final_issues,
            summary="assembled artifact is structurally complete" if not final_issues else "; ".join(final_issues),
            data={"issues": final_issues},
        ):
            return self._reject(candidate)

        try:
            primary, elapsed = _timed(self.agents.classify, spec, candidate.problem_latex)
        except Exception as exc:
            return self._fail(candidate, "classification", exc)
        candidate.classification = primary.model_dump(mode="json")
        classification_passed = (
            primary.subject == spec.subject and primary.question_type == spec.question_type.value
        )
        if not self._gate(
            candidate,
            gate="classification",
            required=True,
            passed=classification_passed,
            summary=(
                "independent subject/type classification matches the specification"
                if classification_passed
                else f"classified as {primary.subject}/{primary.question_type}, expected "
                f"{spec.subject}/{spec.question_type.value}"
            ),
            data=candidate.classification,
            duration_ms=elapsed,
        ):
            return self._reject(candidate)

        try:
            agreement, elapsed = _timed(
                self.agents.verify_answer,
                spec,
                candidate.problem_latex,
                candidate.draft_solution_latex,
                candidate.independent_solution_latex,
            )
        except Exception as exc:
            return self._fail(candidate, "answer_agreement", exc)
        candidate.answer_agreement = agreement.model_dump(mode="json")
        if not self._gate(
            candidate,
            gate="answer_agreement",
            required=True,
            passed=agreement.passed,
            summary=agreement.reasoning,
            data=candidate.answer_agreement,
            duration_ms=elapsed,
        ):
            return self._reject(candidate)

        try:
            alignment, elapsed = _timed(
                self.agents.verify_spec,
                spec,
                candidate.problem_latex,
                candidate.independent_solution_latex,
            )
        except Exception as exc:
            return self._fail(candidate, "spec_alignment", exc)
        candidate.spec_alignment = alignment.model_dump(mode="json")
        if not self._gate(
            candidate,
            gate="spec_alignment",
            required=True,
            passed=alignment.passed,
            summary=alignment.reasoning,
            data=candidate.spec_alignment,
            duration_ms=elapsed,
        ):
            return self._reject(candidate)

        try:
            difficulty, elapsed = _timed(
                self.agents.assess_difficulty,
                spec,
                candidate.final_latex,
                primary,
            )
        except Exception as exc:
            return self._fail(candidate, "difficulty", exc)
        candidate.difficulty = difficulty.model_dump(mode="json")
        observed = float(difficulty.difficulty_score)
        tolerance = spec.acceptance.difficulty_tolerance
        difficulty_passed = abs(observed - spec.difficulty) <= tolerance
        if not self._gate(
            candidate,
            gate="difficulty",
            required=True,
            passed=difficulty_passed,
            summary=f"observed difficulty {observed:.1f}/10; target {spec.difficulty}/10 ± {tolerance}",
            data=candidate.difficulty,
            duration_ms=elapsed,
        ):
            return self._reject(candidate)

        if candidate.idea_latex:
            candidate.final_latex = candidate.final_latex.rstrip() + "\n\n" + candidate.idea_latex

        try:
            compile_result, elapsed = _timed(
                self.agents.compile,
                spec,
                candidate.final_latex,
                self.render_dir,
            )
        except Exception as exc:
            return self._fail(candidate, "compile", exc)
        if not self._gate(
            candidate,
            gate="compile",
            required=True,
            passed=bool(compile_result.get("success")),
            summary=(compile_result.get("error_summary") or "LaTeX compiled successfully"),
            data=compile_result,
            duration_ms=elapsed,
        ):
            return self._reject(candidate)

        try:
            review, elapsed = _timed(self.agents.review, spec, candidate.final_latex)
        except Exception as exc:
            return self._fail(candidate, "review", exc)
        candidate.review = review.model_dump(mode="json")
        if not self._gate(
            candidate,
            gate="review",
            required=True,
            passed=bool(review.passed),
            summary=review.summary,
            data=candidate.review,
            duration_ms=elapsed,
        ):
            return self._reject(candidate)

        if spec.source_kind is SourceKind.VARIANT:
            exact_only = spec.variant_family is VariantFamily.NUMERICAL
            if spec.acceptance.human_review_required:
                novelty, elapsed = _timed(
                    self.novelty_index.check_variant,
                    candidate.problem_latex,
                    spec.acceptance.novelty_threshold,
                    parent_id=spec.parent_spec_id,
                    exact_only=exact_only,
                )
            else:
                novelty, elapsed = _timed(
                    self.novelty_index.check_variant_and_add,
                    spec.spec_id,
                    candidate.problem_latex,
                    spec.acceptance.novelty_threshold,
                    parent_id=spec.parent_spec_id,
                    exact_only=exact_only,
                )
        else:
            novelty_function = (
                self.novelty_index.check
                if spec.acceptance.human_review_required
                else self.novelty_index.check_and_add
            )
            novelty_args = (
                (candidate.problem_latex, spec.acceptance.novelty_threshold)
                if spec.acceptance.human_review_required
                else (spec.spec_id, candidate.problem_latex, spec.acceptance.novelty_threshold)
            )
            novelty, elapsed = _timed(novelty_function, *novelty_args)
        if novelty.mode == "exact_variant":
            novelty_summary = (
                "variant artifact is unique among accepted artifacts"
                if novelty.passed
                else f"variant artifact duplicates accepted item {novelty.closest_id}"
            )
        else:
            novelty_summary = (
                f"maximum blueprint similarity {novelty.max_similarity:.3f}"
                + (f" to {novelty.closest_id}" if novelty.closest_id else "")
            )
        if not self._gate(
            candidate,
            gate="novelty",
            required=True,
            passed=novelty.passed,
            summary=novelty_summary,
            data={
                "max_similarity": novelty.max_similarity,
                "closest_id": novelty.closest_id,
                "threshold": (
                    None
                    if novelty.mode == "exact_variant"
                    else spec.acceptance.novelty_threshold
                ),
                "mode": novelty.mode,
            },
            duration_ms=elapsed,
        ):
            return self._reject(candidate)

        candidate.status = (
            CandidateStatus.NEEDS_REVIEW
            if spec.acceptance.human_review_required
            else CandidateStatus.ACCEPTED
        )
        candidate.completed_at = _now()
        return candidate

    @staticmethod
    def _gate(
        candidate: AuthoredCandidate,
        *,
        gate: str,
        required: bool,
        passed: bool,
        summary: str,
        data: dict[str, Any] | None = None,
        duration_ms: int = 0,
    ) -> bool:
        candidate.gates.append(
            GateResult(
                gate=gate,
                required=required,
                passed=passed,
                summary=summary,
                data=data or {},
                duration_ms=duration_ms,
            )
        )
        return passed or not required

    @staticmethod
    def _reject(candidate: AuthoredCandidate) -> AuthoredCandidate:
        candidate.status = CandidateStatus.REJECTED
        candidate.completed_at = _now()
        return candidate

    @staticmethod
    def _fail(candidate: AuthoredCandidate, stage: str, exc: Exception) -> AuthoredCandidate:
        candidate.status = CandidateStatus.FAILED
        candidate.error_stage = stage
        candidate.error_message = f"{type(exc).__name__}: {exc}"
        candidate.completed_at = _now()
        candidate.gates.append(
            GateResult(
                gate=stage,
                passed=False,
                summary=candidate.error_message,
                data={"exception_type": type(exc).__name__},
            )
        )
        return candidate


def _assemble_problem_diagram(problem_latex: str, diagram_code: str) -> str:
    if has_main_diagram_placeholder(problem_latex):
        return replace_main_diagram_placeholder(problem_latex, diagram_code)
    return problem_latex.rstrip() + "\n\n\\begin{center}\n" + diagram_code.strip() + "\n\\end{center}"


def _extract_solution(final_latex: str) -> str:
    match = re.search(r"\\begin\{solution\}.*?\\end\{solution\}", final_latex, re.DOTALL)
    return match.group(0).strip() if match else ""


def _timed(function: Callable, *args, **kwargs):
    started = time.perf_counter()
    result = function(*args, **kwargs)
    elapsed = max(0, round((time.perf_counter() - started) * 1000))
    return result, elapsed


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _aggregate_usage(events: list[dict[str, Any]]) -> dict[str, Any]:
    completed = [event for event in events if event.get("event") == "completed"]
    totals = {
        "requests": 0,
        "input_tokens": 0,
        "output_tokens": 0,
        "cached_tokens": 0,
        "cache_write_tokens": 0,
        "reasoning_tokens": 0,
        "duration_seconds": 0.0,
    }
    by_agent: list[dict[str, Any]] = []
    for event in completed:
        tokens = event.get("tokens") or {}
        totals["requests"] += int(tokens.get("requests", 0) or 0)
        totals["input_tokens"] += int(tokens.get("input", 0) or 0)
        totals["output_tokens"] += int(tokens.get("output", 0) or 0)
        totals["cached_tokens"] += int(tokens.get("cached", 0) or 0)
        totals["cache_write_tokens"] += int(tokens.get("cache_write", 0) or 0)
        totals["reasoning_tokens"] += int(tokens.get("reasoning", 0) or 0)
        totals["duration_seconds"] += float(event.get("duration", 0.0) or 0.0)
        by_agent.append(
            {
                "agent": event.get("agent"),
                "stage": event.get("stage"),
                "model": event.get("model"),
                "reasoning_effort": event.get("reasoning_effort"),
                "duration_seconds": event.get("duration", 0.0),
                "tokens": tokens,
                "cache_group_id": event.get("cache_group_id"),
            }
        )
    totals["duration_seconds"] = round(totals["duration_seconds"], 4)
    return {"totals": totals, "agents": by_agent}
